
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-tickers}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB:-tickers}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  app:
    build:
      context: .
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-dev}
        BUILD_TIME: ${BUILD_TIME:-unknown}
    environment:
      PORT: "8080"
      GIN_MODE: "release"
      # Внутри сети compose хост БД это имя сервиса "db"
      DB_DSN: "postgresql://postgres:${POSTGRES_PASSWORD:-pass}@db:5432/${POSTGRES_DB:-tickers}?sslmode=disable"
      ADMIN_API_KEY: supersecret
      ADMIN_TRUSTED_CIDRS: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.1/32,::1/128
      ADMIN_REQUIRE_BOTH: 0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata: {}
